# Generated by Django 4.2.3 on 2023-08-14 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0002_skill_type_exercise'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='video_link',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
