# Generated by Django 4.2.3 on 2023-08-22 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0003_exercise_video_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='Measurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
        ),
    ]
