# Generated by Django 4.2.3 on 2023-08-22 00:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0004_measurement'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='quality_measurement',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exercises', to='practice.measurement'),
        ),
    ]
