# Generated by Django 4.2.3 on 2023-08-22 01:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0005_exercise_quality_measurement'),
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('note', models.CharField(blank=True, max_length=512, null=True)),
                ('quality_rating', models.IntegerField()),
                ('length', models.IntegerField()),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='practice.exercise')),
            ],
        ),
    ]
