# Generated by Django 4.2.3 on 2023-08-23 22:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0007_record_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exercises', to='practice.user'),
        ),
        migrations.AddField(
            model_name='exercise',
            name='privacy',
            field=models.CharField(choices=[('PV', 'Private'), ('PB', 'Public'), ('UL', 'Unlisted')], default=1, max_length=2),
            preserve_default=False,
        ),
    ]
