# Generated by Django 4.2.3 on 2023-08-23 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0008_exercise_creator_exercise_privacy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='privacy',
            field=models.CharField(choices=[('PV', 'Private'), ('PB', 'Public'), ('UL', 'Unlisted')], default='PV', max_length=2),
        ),
    ]
